### ISSUE TITLE
Error when generating payment url

### ISSUE THREAD

**Issue by cirilo007** [quentingosset/olkypay-php-sdk#1]
Hi there,

No problem to create a payer and an order, but I have an error when trying to generate the payment url : 

```
{
  "errorCode" : "PAYLINE_ERROR",
  "httpCode" : "Bad Request",
  "exceptionType" : "ServerResponseException",
  "message" : "PAYLINE_ERROR"
}
```

Any ideas ?
Thanks in advance

**Comment by quentingosset** [comment]
hi @cirilo007, after some tests on my side, I have no problem regarding the generation of payment links. What I can recommend is to check with OlkyPay if your account is well configured because I already had problems that ended with a bad setting on the side of OlkyPay. If everything is OK, please check if your server is correctly configured and accept at OlkyPay because after a few tests with PostMan, I arrive at the same conclusion as you, I manage to do everything except the "doPayement" however on the server in production which uses the API, the same code executes without error the "doPayment". I added you my test code in the repo :)

**Comment by cirilo007** [comment]
Thanks Quentin ! Looks like OlkyPay sandbox server (uat-ws.olkypay.com) is having connectivity issues and 404 errors when calling the WS. I've contacted them and waiting to hear from them. Nothing related to your class, which came out pretty handy to integrate the payement solution, thanks for sharing !

**Comment by quentingosset** [comment]
No worries :) hoping that this will be settled quickly for you.
